### ISSUE TITLE
Training fails with CUDA_ERROR_INVALID_HANDLE

### ISSUE THREAD

**Issue by skye-harris** [TaterTotterson/microWakeWord-Trainer-Nvidia-Docker#30]
Hi there,

Went to try this out today but unfortunately it crashes when it goes to run the training.

My server is running:
Operating System: Ubuntu 24.04.3 LTS
Kernel: Linux 6.14.0-37-generic
Architecture: x86-64
GPU: 16GB RTX 5060 Ti (Blackwell)

CUDA is fully setup and working, 14.5GB VRAM free at the time, but does not appear to be memory related.

Training log
```
================================================================================
===== Recorder Training Run =====
================================================================================

================================================================================
===== Ensuring training datasets (setup_training_datasets) =====
→ bash -lc cd '/data' && '/root/mww-scripts/cli/setup_training_datasets' --cleanup-archives='false' --cleanup-intermediate-files='false' --data-dir='/data'
===== Setting up Training Datasets =====

===== Checking negative datasets: dinner_party dinner_party_eval no_speech speech =====
   Existing dinner_party valid
   Existing dinner_party_eval valid
   Existing no_speech valid
   Existing speech valid
   Negative datasets complete
===== Checking MIT_RIR =====
   Existing ./mit_rirs_16k valid
   MIT_RIR complete
***** Checking audioset *****
   Existing ./audioset_16k present (18683 wav); skipping extract/convert
   Audioset complete
***** Checking FMA *****
   Existing FMA valid
   FMA complete
================================================================================
                                   Training dataset setup  Elapsed time: 0:00:00
================================================================================
================================================================================
===== Running 'hey_lay_zell(Hey Lay Zell)' generation, augmentation and training =====
                 GPU Name: NVIDIA GeForce RTX 5060 Ti
       Compute Capability:    12.0
Streaming Multiprocessors:      36
        CUDA Cores per SM:     128
         Total CUDA Cores:    4608
             Total Memory:   15846 mb
              Free Memory:   14550 mb

Sample generation not required

Augmentation not required

ℹ️  No personal features found at /data/work/personal_augmented_features/training (continuing without personal weighting)
===== Starting 40000 training steps =====
   Wrote training_parameters.yaml

================================================================================
===== Attempt 1/2: GPU training (allow_growth + cuda_malloc_async) =====
================================================================================
→ python -m microwakeword.model_train_eval --training_config /data/work/trained_models/training_parameters.yaml --train 1 --restore_checkpoint 1 --test_tf_nonstreaming 0 --test_tflite_nonstreaming 0 --test_tflite_nonstreaming_quantized 0 --test_tflite_streaming 0 --test_tflite_streaming_quantized 1 --use_weights best_weights mixednet --pointwise_filters 64,64,64,64 --repeat_in_block 1,1,1,1 --mixconv_kernel_sizes [5], [7,11], [9,15], [23] --residual_connection 0,0,0,0 --first_conv_filters 32 --first_conv_kernel_size 5 --stride 2
   Loading and analyzing data sets.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1769661450.821938    1048 gpu_device.cc:2431] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
W0000 00:00:1769661450.825380    1048 gpu_device.cc:2431] TensorFlow was not built with CUDA kernel binaries compatible with compute capability 12.0. CUDA kernels will be jit-compiled from PTX, which could take 30 minutes or longer.
I0000 00:00:1769661450.947652    1048 gpu_process_state.cc:208] Using CUDA malloc Async allocator for GPU: 0
I0000 00:00:1769661450.948555    1048 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 12749 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 5060 Ti, pci bus id: 0000:01:00.0, compute capability: 12.0
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/data/tools/microWakeWord/microwakeword/model_train_eval.py", line 405, in <module>
    model = model_module.model(
            ^^^^^^^^^^^^^^^^^^^
  File "/data/tools/microWakeWord/microwakeword/mixednet.py", line 318, in model
    net = stream.Stream(
          ^^^^^^^^^^^^^^
  File "/data/.venv/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/data/tools/microWakeWord/microwakeword/layers/stream.py", line 335, in build
    wrapped_cell.build(tf.TensorShape(faked_stream_dim_shape))
tensorflow.python.framework.errors_impl.InternalError: {{function_node __wrapped__Cast_device_/job:localhost/replica:0/task:0/device:GPU:0}} 'cuLaunchKernel(function, gridX, gridY, gridZ, blockX, blockY, blockZ, 0, reinterpret_cast<CUstream>(stream), params, nullptr)' failed with 'CUDA_ERROR_INVALID_HANDLE' [Op:Cast] name: 
⚠️  GPU attempt failed. Checking whether this looks like a GPU/OOM/runtime failure…
❌ Training failed (does not look GPU/OOM/runtime). See: /data/output/2026-01-29-04-37-08-hey_lay_zell-50000-40000/logs/training.log
```

Thanks in advance.

**Comment by skye-harris** [comment]
> could it be that it didn't see your GPU and therefore didn't use it?

Unlikely, given nvtop showed it using both vram and compute.  It was just very slow and no faster than running on CPU.

**Comment by TaterTotterson** [comment]
@loryanstrant your running on Ubuntu and having errors?

Will you attach your log?

I’ve ignored a lot of these issues because most of them are windows docker errors

**Comment by loryanstrant** [comment]
> Also if your just wanting a mmw this repo is automated
> 
> https://github.com/TaterTotterson/microWakeWords

I saw this, and saw that you had Cortana (which is what I want), but as I'm an Australian I figured the one you had there probably wouldn't work with my accent.

After a whole lot of attempts to do this, it looks like TF 2.21 PTX JIT for CC 12.0a works correctly whereas 2.18 for CC 12.0 has the fail.
I'm doing a test of my build now and will let you know how it goes.

**Comment by loryanstrant** [comment]
> I pushed a update that might fix the Blackwell issue.... let me know

Have just pulled down the updated image and am testing it out now.

**Comment by loryanstrant** [comment]
Confirmed it works, but I think it used primarily CPU and only a small bit of GPU. It only took 36mins, but I watched my CPU burn while the GPU barely lifted a finger (if at all).
Unfortunately I wasn't logging the utilisation while it worked, as I wanted to see if it finished or not.

**Comment by skye-harris** [comment]
Pulled down the latest docker image and have it reinstalling the dependencies and tools etc now (which takes a little while each time I do this). Will update once the run completes - hopefully quicker than the ~6hours it normally takes to run :)

**Comment by skye-harris** [comment]
40minutes!!! The one I kicked off earlier is still running... the processes haven't appeared in nvtop whatsoever this time though so it looks like it's just doing a fully CPU run

Full log (so far, as its still running) in a gist [here](https://gist.github.com/skye-harris/d65579ac7106231343f050737d70c755), but it does recognise the GPU:

>    Nvidia GPU detected
   Blackwell GPU detected (compute capability 12.0)


> ===== Testing Cuda =====
> 
> GPU Name: NVIDIA GeForce RTX 5060 Ti
> Compute Capability:    12.0
> Streaming Multiprocessors:      36
>         CUDA Cores per SM:     128
>          Total CUDA Cores:    4608
>              Total Memory:   15846 mb
>               Free Memory:   11152 mb
> 
> ===== Testing Tensorflow =====
> 
> GPU: Not available
> CPU: Available - /job:localhost/replica:0/task:0/device:CPU:0
> 
> ===== Testing Torch =====
> 
> GPU: Available - NVIDIA GeForce RTX 5060 Ti
> CPU: Available
> 
> ===== Testing onnxruntime =====
> 
> GPU: Available
> CPU: Available
> TensorRT: Available

**Comment by skye-harris** [comment]
I already had most of the training data already downloaded from prior runs, only needed the new ones, and took about an hour. The last 3+ hours since has it just running training on CPU without anything having seemingly run on GPU at all. Training runs typically take about 6 hours on my servers old CPU (a 7th-gen 4-core i5) which is why I've been hoping to be able to throw the GPU at the problem

**Comment by skye-harris** [comment]
It should appear in nvtop, utilising both vram and compute though, will it not? Because it hasn't whatsoever... it has pegged all 4 cpu cores at 100% for periods of time tho.

It has not used any GPU resources over the past almost 5 hours. I dont know what to tell you... absolutely zero GPU usage.

Surely I should be seeing... something? Even @Omega-sko's docker image utilised vram and compute on the GPU, albeit with no actual gain in performance over a pure CPU-only run.. but I am seeing zero GPU utilisation from the latest pull here.

**Comment by skye-harris** [comment]
> No the model is only 64k it trains in a flash, that’s why I mentioned cpu and gpu training are about the same speed

I think I built up my expectations on a performance increase by myself and disappointed myself there :) If its as expected then you may as well close of the issue as it does run and not crash, although personally I'll just stick to CPU training so I don't have to unload my LLM for the long training duration (which tbh maybe I didnt need to be doing anyway lol... but I had noted vram usage on the other image I was testing) :)

> Also you’ll have to tell me how well the de works it only uses 5 voices vs the 900 on English uses

Hmm I dont recall changing it away from English... this should have been an English run, but maybe I accidentally changed it and hadn't noticed. Contents of the `wake_word_samples` folder are all dated from a prior run back on the 1st of March, and are all in English piper voices though and the wake word is working better than previous attempts, so no complaints there.

Is it possible to re-use the personal recordings in future training runs, and augment these with additional samples?

**Comment by skye-harris** [comment]
> Well if your doing a new word you have to have new records of you saying the new word 😄

But if doing new runs of the existing word, augmented with additional samples, it would be much more convenient to just re-use the existing 50 recordings and only record additional ones to augment it, or add additional speakers to this.

**Comment by Omega-sko** [comment]
Hi @TaterTotterson @skye-harris @loryanstrant,

I tested the latest version from TaterTotterson again on my system.
Note: My container is running on Windows via docker.desktop.

RAM = 2 x 16 GB Kingston DDR5-5600 - 2800MHz
CPU = Intel(R) Core(TM) Ultra 9 275HX
GPU = NVIDIA GeForce RTX 5070 Ti Laptop 12 GB RAM

For me, it always fell back to the CPU.

I also made changes to `cli/setup_python_venv`, `cli/wake_word_sample_trainer`, and `train_wake_word`, partly with the help of Copilot, because the current image from TaterTotterson didn't correctly detect my GPU, resulting in the installation of the TensorFlow stack (tensorflow==2.20.0) instead of the TensorFlow stack (tf-nightly[and-cuda]). I also expanded the logging in case of errors.

An important adjustment for me was also necessary in the Dockerfile of the base system, because otherwise the training was done with the CPU instead of the GPU. I changed `base "FROM ubuntu:24.04"` to `FROM nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04`.

This makes the image significantly larger, but I suspect that the "FROM ubuntu:24.04" base is missing some modules, preventing the GPU training from working correctly on RTX 50xx and later models.

I created the image in this repository, and it runs on the GPU for me. However, I don't know if this is generally the case. If anyone else is currently only getting CPU-based training, please feel free to test it and report back:

docker pull ghcr.io/omega-sko/microwakeword:main-beta


I started the container via "docker-compose.yml".

```docker-compose.yml
services:
  microwakeword:
    image: ghcr.io/omega-sko/microwakeword:main-dev
    container_name: microwakeword-recorder-omega-main-dev
    environment:
      - REC_PORT=8789
    ports:
      - "8888:8789"
    volumes:
      - "E:/Docker/mWW-main-beta:/data"
    entrypoint: ["bash"]
    command: ["-lc", "./run_recorder.sh"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
```


Command (path in my case, must be adjusted):

E:\Docker\mWW-main-beta> docker compose -f docker-compose.yml up

**Comment by loryanstrant** [comment]
Thanks for doing that @Omega-sko. 
Other than what I documented was the fix for my instance, I found with the latest image from @TaterTotterson that the processing time between it using mainly GPU vs CPU was much of a muchness (~35mins). 
And given I only wanted to train up a single word, I've achieved my goal. 

But thank you for your efforts!

**Comment by Hotzigetty** [comment]
> Thanks for doing that [@Omega-sko](https://github.com/Omega-sko). Other than what I documented was the fix for my instance, I found with the latest image from [@TaterTotterson](https://github.com/TaterTotterson) that the processing time between it using mainly GPU vs CPU was much of a muchness (~35mins). And given I only wanted to train up a single word, I've achieved my goal.
> 
> But thank you for your efforts!

I've been getting the same GPU OOM errors on docker (debian) - so I thought I'd run it on CPU only: in this case, do you recall how much memory was needed? Cheers and thanks in advance!

**Comment by loryanstrant** [comment]
Sorry no, I wasn't paying attention to RAM usage.

**Comment by skye-harris** [comment]
Closing this as the original issue was resolved :)
